require:
  - rubocop-performance

AllCops:
  Exclude:
    - 'bin/*'
    - "db/*"
    - "config/**/"
    - "db/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
  Max: 30
  
  Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb # nearly all spec files go over 25 lines

Metrics/MethodLength:
  Max: 20

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  # If `true`, strings which span multiple lines using `\` for continuation must
  # use the same type of quotes on each line.
  ConsistentQuotesInMultiline: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RedundantAssignment: # (new in 0.87)
  Enabled: true

Style/RedundantFetchBlock: # (new in 0.86)
  Enabled: true

Style/RedundantFileExtensionInRequire: # (new in 0.88)
  Enabled: true

Style/RedundantSelfAssignment: # (new in 0.90)
  Enabled: true

Style/SingleArgumentDig: # (new in 0.89)
  Enabled: true

Style/SoleNestedConditional: # (new in 0.89)
  Enabled: true

Style/StringConcatenation: # (new in 0.89)
  Enabled: true

Performance/AncestorsInclude: # (new in 1.7)
  Enabled: true

Performance/BigDecimalWithNumericArgument: # (new in 1.7)
  Enabled: true

Performance/RedundantSortBlock: # (new in 1.7)
  Enabled: true

Performance/RedundantStringChars: # (new in 1.7)
  Enabled: true

Performance/ReverseFirst: # (new in 1.7)
  Enabled: true

Performance/SortReverse: # (new in 1.7)
  Enabled: true

Performance/Squeeze: # (new in 1.7)
  Enabled: true

Performance/StringInclude: # (new in 1.7)
  Enabled: true

Performance/Sum: # (new in 1.8)
  Enabled: true

Style/Documentation:
  Enabled: false