version: "3.8"
services:
  database:
    image: postgres:14-alpine
    volumes:
      - .docker/db/data:/var/lib/postgresql/data
      - .docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
  backend:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    env_file:
      - .env
    volumes:
      -  $PWD:/app
    ports:
      - "3000:3000"
    depends_on:
      - database

volumes:
  db_data: