default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("PG_HOST") { "db" } %>
  port: <%= ENV.fetch("PG_PORT") { 5432 } %>
  username: <%= ENV.fetch("PG_USER") { "root" } %>
  password: <%= ENV.fetch("PG_PASSWORD") { "root" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: schools_dev

test:
  <<: *default
  database: schools_test